<div class="form">
	<form action="" method="post" class="form_action">
		<div class="new_bid">
			<header>
				<h1>Новая заявка</h1>
			</header>
			<div class="bid">
				<p>
					<label for="name">Название<span class="required">*</span></label>
					<input type="text" id="name">
				</p>
				<p>
					<label for="description">Описание</label>
					<input type="text" id="description">
				</p>
				<div class="statuss">
					<p>
						<label for="status">Статус</label>
						<select name="status" id="status">
							<option value="open">Открыта</option>
							<option value="in_work">В работе</option>
							<option value="close">Закрыта</option>
							<option value="canceled">Отменена</option>
						</select>
					</p>
					<p>
						<label for="priority">Приоритет<span class="required">*</span></label>
						<select name="priority" id="priority">
							<option value="low">Низкий</option>
							<option value="average">Средний</option>
							<option value="high">Высокий</option>
							<option value="critical">Критический</option>
						</select>
					</p>
					<p>
						<label for="topic">Срок<span class="required">*</span></label>
						<input type="date" name="date">
					</p>
				</div>
				<div class="file">
					<label for="topic">Вложенные файлы:</label>
					<div class="right_file">
						<input type="file" name="file">
						<input type="file" name="screen">
					</div>
				</div>
				<div class="comments">
					<label for="comment">Добавить комментарий</label>
					<input type="text" name="comment" id="comment">
				</div>
				<div class="saveBid">
					<input type="submit" value="сохранить">
				</div>

			</div>
		</div>
		<div class="applicant">
			<header>
				<h1>Заявитель</h1>
				<input type="text">
			</header>
			<header>
				<h1>Исполнитель</h1>
				<input type="text">
			</header>
		</div>
	</form>
</div>
<div class="clear"></div>


