<?php print_r($data) ?>
<div class="form">
	<form action="insert" method="post" class="form_action" enctype="multipart/form-data">
		<div class="new_bid">
			<header>
				<h1>Новая заявка</h1>
			</header>
			<div class="bid">
				<p<?=$data['name']['val']?>>
					<label for="name">Название<span class="required">*</span></label>
					<input type="text" name="name" id="name" value='<?=$data['name']['name']?>' placeholder="название заявки">
				</p>
				<p<?=$data['description']['val']?>>
					<label for="description">Описание<span class="required">*</span></label>
					<input type="text" name="description" value='<?=$data['description']['name']?>' placeholder="описание заявки" id="description">
				</p>
				<div class="statuss">
					<p<?=$data['status']['val']?>>
						<label for="status">Статус</label>
						<select name="status" id="status" disabled>
							<option value="open">Открыта</option>
							<option value="in_work">В работе</option>
							<option value="close">Закрыта</option>
							<option value="canceled">Отменена</option>
						</select>
					</p>
					<p<?=$data['priority']['val']?>>
						<label for="priority">Приоритет</span></label>
						<select name="priority" id="priority">
							<option value="low" <?php if($data['priority']['name'] === 'low')echo'selected'?>>Низкий</option>
							<option value="average"  <?php if($data['priority']['name'] === 'average')echo'selected'?>>Средний</option>
							<option value="high"  <?php if($data['priority']['name'] === 'high')echo'selected'?>>Высокий</option>
							<option value="critical" <?php if($data['priority']['name'] === 'critical')echo'selected'?>>Критический</option>
						</select>
					</p>
					<p>
						<label for="date">Срок</label>
						<input type="datetime-local" id="date" name="date">
					</p>
				</div>
				<div class="file">
					<label for="topic">Вложенные файлы:</label>
					<div class="right_file">
						<input type="hidden" name="MAX_FILE_SIZE" value="30000" />
						<input type="file" name="file">
						<input type="file" name="screen">
					</div>
				</div>
				<div class="comments">
					<label for="comment">Добавить комментарий</label>
					<input type="text" name="comment"  id="comment" placeholder="напишите свой комментарий">
				</div>
				<div class="saveBid">
					<input type="submit" name="saveBid" value="сохранить">
				</div>
			</div>
		</div>
		<div class="applicant">
			<header<?=$data['applicant']['val']?>>
				<h1>Заявитель<span class="required">*</span></h1>
				<input type="text" name="applicant" value='<?=$data['applicant']['name']?>' placeholder="заявитель">
			</header>
			<header<?=$data['implementer']['val']?>>
				<h1>Исполнитель<span class="required">*</span></h1>
				<input type="text" name="implementer" value='<?=$data['implementer']['name']?>' placeholder="заявитель">
			</header>
		</div>
	</form>
</div>
<div class="clear"></div>


