<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css"  href="http://<?=HOST?>/<?=DIR_PROJECT?>/public/css/style.css">
</head>
<body>
<div class="wrapper">
	<div class="sidebar">
		<?=$this->_helpers_menu?>
	</div>
	<div class="content">
		<?=$this->_content?>
	</div>
</div>
</body>
<script type="text/javascript" src="http://<?=HOST?>/<?=DIR_PROJECT?>/public/js/html5shiv.js"></script>
</html>