<div class="authorization">
	<header>
		<h1>Авторизация</h1>
		<?php if($data['message']):?>
			<h3>Неправильный логин или пароль!</h3>
		<?php endif; ?>
	</header>
	<form class="subform"  method="post" action="check">
		<p>
			<label for="login">Логин</label>
			<input type="text" name="login" id="login">
		</p>
		<p>
			<label for="password">Пароль</label>
			<input type="mail" name="password" id="password">
		</p>
		<p>
			<input type="submit" name="authorization" value="войти">
		</p>
	</form>
</div>